CLOUD_API_KEY: '374232253519653'
CLOUD_API_SECRET: 'KbbQIX1zY1T5obFsPPkyc0e2yXc'
CLOUD_NAME: 'dyw3jnf2p'
FACEBOOK_APP_ID: '1495646454073290'
FACEBOOK_APP_SECRET: 'a3cbf4a4d6ad63abddb3ddfde34aa6b1'
TWITTER_APP_KEY: 'YqbpRLhFqt8Sn0nz5GQVX5ldQ'
TWITTER_APP_SECRET: 'Ggzkeud7jw0oEeSQXq1xul754v9jh2Sbg62U3G9AF28yy7fEVX'